# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Management Covid' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'Alamofire', '~> 5.1'
  pod 'JWTDecode', '~> 2.4'
  pod 'SDWebImage'
  # Pods for Management Covid

  target 'Management CovidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Management CovidUITests' do
    # Pods for testing
  end

end
